In [1]:
import pandas as pd

In [2]:
loc1 = pd.read_csv("loc1.txt", sep=" ")
loc2 = pd.read_csv("loc2.txt", sep=" ")
loc3 = pd.read_csv("loc3.txt", sep=" ")

In [3]:
def analyze_loc(loc):
	print("head:", loc.head())
	print("info:", loc.info())
	print("describe:", loc.describe())
	print("isnull:", loc.isnull())

In [4]:
analyze_loc(loc1)

head:    ind     id         f0         f1        f2     product
0    0  kBEdx -15.001348  -8.276000 -0.005876    3.179103
1    1  62mP7  14.272088  -3.475083  0.999183   26.953261
2    2  vyE1P   6.263187  -5.948386  5.001160  134.766305
3    3  KcrkZ -13.081196 -11.506057  4.999415  137.945408
4    4  AHL4O  12.702195  -8.147433  5.004363  134.766305
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ind      40 non-null     int64
 1   id       40 non-null     object
 2   f0       40 non-null     float64
 3   f1       40 non-null     float64
 4   f2       40 non-null     float64
 5   product  40 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 2.0+ KB
info: None
describe:              ind         f0         f1         f2     product
count  40.000000  40.000000  40.000000  40.000000   40.000000
mean   19.500000   2.077724  -4.821013   2.899393   79.675956
std    11.690452   8.823711   4.101341   1.721036   46.426570
min     0.000000 -15.001348 -13.659814  -0.007630    0.000000
25%     9.750000  -4.478392  -7.714120   2.002661   53.906522
50%    19.500000   2.460140  -4.793330   2.995529   84.038886
75%    29.250000   9.596212  -2.119299   4.250260  116.935687
max    39.000000  16.320755   2.944454   5.004363  137.945408
isnull:       ind     id     f0     f1     f2  product
0   False  False  False  False  False    False
1   False  False  False  False  False    False
2   False  False  False  False  False    False
3   False  False  False  False  False    False
4   False  False  False  False  False    False
5   False  False  False  False  False    False
6   False  False  False  False  False    False
7   False  False  False  False  False    False
8   False  False  False  False  False    False
9   False  False  False  False  False    False
10  False  False  False  False  False    False
11  False  False  False  False  False    False
12  False  False  False  False  False    False
13  False  False  False  False  False    False
14  False  False  False  False  False    False
15  False  False  False  False  False    False
16  False  False  False  False  False    False
17  False  False  False  False  False    False
18  False  False  False  False  False    False
19  False  False  False  False  False    False
20  False  False  False  False  False    False
21  False  False  False  False  False    False
22  False  False  False  False  False    False
23  False  False  False  False  False    False
24  False  False  False  False  False    False
25  False  False  False  False  False    False
26  False  False  False  False  False    False
27  False  False  False  False  False    False
28  False  False  False  False  False    False
29  False  False  False  False  False    False
30  False  False  False  False  False    False
31  False  False  False  False  False    False
32  False  False  False  False  False    False
33  False  False  False  False  False    False
34  False  False  False  False  False    False
35  False  False  False  False  False    False
36  False  False  False  False  False    False
37  False  False  False  False  False    False
38  False  False  False  False  False    False
39  False  False  False  False  False    False

In [5]:
analyze_loc(loc2)

head:    ind     id        f0        f1        f2     product
0    0  fwXo0 -1.146987  0.963328 -0.828965   27.758673
1    1  WJtFt  0.262778  0.269839 -2.530187   56.069697
2    2  ovLUW  0.194587  0.289035 -5.586433   62.871910
3    3  q6cA6  2.236060 -0.553760  0.930038  114.572842
4    4  WPMUX -0.515993  1.716266  5.899011  149.600746
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ind      40 non-null     int64
 1   id       40 non-null     object
 2   f0       40 non-null     float64
 3   f1       40 non-null     float64
 4   f2       40 non-null     float64
 5   product  40 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 2.0+ KB
info: None
describe:              ind         f0         f1         f2     product
count  40.000000  40.000000  40.000000  40.000000   40.000000
mean   19.500000  -0.074466   0.085683   2.523979   86.420739
std    11.690452   1.270211   1.523828   3.346449   38.600008
min     0.000000  -2.628353  -3.503145  -5.586433    8.704162
25%     9.750000  -1.163853  -0.663680   0.872270   56.376105
50%    19.500000  -0.347388   0.215317   2.742131   92.237154
75%    29.250000   0.783358   0.991932   5.239435  110.296892
max    39.000000   2.378418   3.167210   8.635293  166.799132
isnull:       ind     id     f0     f1     f2  product
0   False  False  False  False  False    False
1   False  False  False  False  False    False
2   False  False  False  False  False    False
3   False  False  False  False  False    False
4   False  False  False  False  False    False
5   False  False  False  False  False    False
6   False  False  False  False  False    False
7   False  False  False  False  False    False
8   False  False  False  False  False    False
9   False  False  False  False  False    False
10  False  False  False  False  False    False
11  False  False  False  False  False    False
12  False  False  False  False  False    False
13  False  False  False  False  False    False
14  False  False  False  False  False    False
15  False  False  False  False  False    False
16  False  False  False  False  False    False
17  False  False  False  False  False    False
18  False  False  False  False  False    False
19  False  False  False  False  False    False
20  False  False  False  False  False    False
21  False  False  False  False  False    False
22  False  False  False  False  False    False
23  False  False  False  False  False    False
24  False  False  False  False  False    False
25  False  False  False  False  False    False
26  False  False  False  False  False    False
27  False  False  False  False  False    False
28  False  False  False  False  False    False
29  False  False  False  False  False    False
30  False  False  False  False  False    False
31  False  False  False  False  False    False
32  False  False  False  False  False    False
33  False  False  False  False  False    False
34  False  False  False  False  False    False
35  False  False  False  False  False    False
36  False  False  False  False  False    False
37  False  False  False  False  False    False
38  False  False  False  False  False    False
39  False  False  False  False  False    False

In [6]:
analyze_loc(loc3)

head:    ind     id        f0        f1        f2     product
0    0  txEyH  0.705745 -0.497823  1.221170  105.280062
1    1  2acmU  1.334711 -0.340164  4.365080   73.037750
2    2  409Wp  1.022732  0.151990  1.419926   85.265647
3    3  iJLyR -0.032172  0.139033  2.978566  168.620776
4    4  Xdl7t  1.988431  0.155413  4.751769  154.036647
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ind      40 non-null     int64
 1   id       40 non-null     object
 2   f0       40 non-null     float64
 3   f1       40 non-null     float64
 4   f2       40 non-null     float64
 5   product  40 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 2.0+ KB
info: None
describe:              ind         f0         f1         f2     product
count  40.000000  40.000000  40.000000  40.000000   40.000000
mean   19.500000   0.490485   0.233529   2.501777  100.709822
std    11.690452   0.865533   0.538145   3.260147   38.953808
min     0.000000  -1.157504  -0.555728  -5.624670   28.207978
25%     9.750000  -0.021976  -0.138638   0.073990   73.014136
50%    19.500000   0.375989   0.152643   2.580888   92.721689
75%    29.250000   1.002653   0.619811   4.404607  127.598274
max    39.000000   2.173381   1.130622   9.441852  168.620776
isnull:       ind     id     f0     f1     f2  product
0   False  False  False  False  False    False
1   False  False  False  False  False    False
2   False  False  False  False  False    False
3   False  False  False  False  False    False
4   False  False  False  False  False    False
5   False  False  False  False  False    False
6   False  False  False  False  False    False
7   False  False  False  False  False    False
8   False  False  False  False  False    False
9   False  False  False  False  False    False
10  False  False  False  False  False    False
11  False  False  False  False  False    False
12  False  False  False  False  False    False
13  False  False  False  False  False    False
14  False  False  False  False  False    False
15  False  False  False  False  False    False
16  False  False  False  False  False    False
17  False  False  False  False  False    False
18  False  False  False  False  False    False
19  False  False  False  False  False    False
20  False  False  False  False  False    False
21  False  False  False  False  False    False
22  False  False  False  False  False    False
23  False  False  False  False  False    False
24  False  False  False  False  False    False
25  False  False  False  False  False    False
26  False  False  False  False  False    False
27  False  False  False  False  False    False
28  False  False  False  False  False    False
29  False  False  False  False  False    False
30  False  False  False  False  False    False
31  False  False  False  False  False    False
32  False  False  False  False  False    False
33  False  False  False  False  False    False
34  False  False  False  False  False    False
35  False  False  False  False  False    False
36  False  False  False  False  False    False
37  False  False  False  False  False    False
38  False  False  False  False  False    False
39  False  False  False  False  False    False